"""users table

Revision ID: 532adeb789fc
Revises: 48c3f8cb63a1
Create Date: 2019-07-20 14:11:57.348671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '532adeb789fc'
down_revision = '48c3f8cb63a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('usernmae', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_usernmae'), 'user', ['usernmae'], unique=True)
    op.drop_index('ix_user_username', table_name='user')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=64), nullable=True))
    op.create_index('ix_user_username', 'user', ['username'], unique=1)
    op.drop_index(op.f('ix_user_usernmae'), table_name='user')
    op.drop_column('user', 'usernmae')
    # ### end Alembic commands ###
